# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TokboxTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for TokboxTest
  pod 'OpenTok', '2.14.0'

  target 'TokboxTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TokboxTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
